import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("review-pr preserves canonical bare-number identity resolution", async () => {
  const prompt = await readFile("candidate/prompts/review-pr.md", "utf8");
  const skill = await readFile("candidate/skills/forgedock-review-pr/SKILL.md", "utf8");
  const staging = await readFile("candidate/skills/forgedock-review-pr-staging/SKILL.md", "utf8");
  const reviewer = await readFile("candidate/agents/forgedock-reviewer.md", "utf8");
  const helper = await readFile("bin/forgedock-candidate.mjs", "utf8");
  assert.match(prompt, /bare positive PR number/);
  assert.match(prompt, /canonical `forge\.yaml`/);
  assert.match(prompt, /Do not ask for a URL or repository/);
  assert.match(skill, /bare positive PR number/);
  assert.match(skill, /project\.owner\/repo/);
  assert.match(skill, /Ask for clarification only when/);
  assert.match(staging, /policy-accepted `SKIPPED` or `NEUTRAL`/);
  assert.match(staging, /Do not gate on `required \+\s+skipped` alone/);
  assert.match(skill, /minimal `gh pr view`[\s\S]*title, and body/);
  assert.match(skill, /do not make a separate body query/);
  assert.match(skill, /`forge_prepare_review` once/);
  assert.match(skill, /`policy-summary\.json`/);
  assert.match(skill, /returned `request` object is the exact/);
  assert.match(staging, /without rereading the file/);
  assert.match(skill, /If a configured local check must\s+run,[\s\S]*before launching reviewer children/);
  assert.match(skill, /do\s+not weaken clean-tree validation or delete runtime artifacts/);
  assert.match(skill, /`publicationState: unverified` only means the parent has not independently finalized delivery/);
  assert.match(skill, /Do not call the recovery tool to re-verify a role[\s\S]*workflow result already says publication succeeded/);
  assert.match(skill, /After successful final publication[\s\S]*Do not reread the completed decision\/gate artifacts/);
  assert.match(staging, /preserve the same revision[\s\S]*readback-only reconciliation action/);
  assert.match(staging, /include both exact returned permalinks on separate labeled lines[\s\S]*never cite only the gate or a\s+provisional panel/);
  const localCheckPosition = staging.indexOf("configured local check once through");
  const rosterLaunchPosition = staging.indexOf("pass the exact returned request unchanged to");
  assert.ok(localCheckPosition >= 0 && localCheckPosition < rosterLaunchPosition);
  assert.match(staging, /Before\s+launching reviewers, run each relevant configured local check once through\s+`forge_run_check`/);
  assert.match(staging, /clean-tree check reject a later local-check rerun/);
  assert.match(staging, /staging launch\s+hook enforces one attempt per configured check/);
  assert.match(staging, /after launch it blocks check reruns/);
  assert.match(staging, /After preparation, use registered read\/check tools only; do not retry blocked Bash calls/);
  assert.match(staging, /answer through `subagent_supervisor` without launching a new reviewer/);
  assert.match(staging, /mark it completed as the last tool call after verified publication/);
  assert.match(reviewer, /do not send routine `contact_supervisor`\s+progress updates/i);
  assert.match(reviewer, /material unexpected discovery that changes the review plan/);
  assert.match(reviewer, /Preserve those actionable notifications/);
  assert.match(helper, /Do not send routine contact_supervisor progress_update messages/);
  assert.match(helper, /material unexpected discovery that changes the review plan/);
  assert.match(helper, /Preserve those actionable notifications/);
});
